version: "3.5"

services:
  ev:
    build:
      context: ./
      target: base
    container_name: ev_php
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - ev_db
    ports:
      - "5000:80"

  ev_db:
    image: mysql:8.0
    container_name: ev_mysql
    command: --sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_CONNECTION=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ev
      - MYSQL_USERNAME=root
    ports:
      - "5307:3306"
      
  ev_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ev_phpmyadmin
    environment:
      - PMA_HOST=ev_db
    restart: always
    ports:
      - 5001:80
volumes:
    db_data:
